---
title: "Untitled"
author: "Rose Determan"
date: "11/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp) # spatial point data frames
library(gstat) # variogram estimation
library(tmap)
library(geosphere)
library(sf)
library(magrittr)
library(dplyr)


env <- st_read("env/env.shp")
env<-st_centroid(env)
env <- env[!is.na(env$mean_pm25),]




dem <- st_read("Demographics_Smoothed/Demographics_Smoothed/DemographicsSmoothed.shp")

#next steps 
#join selected environment columns to demographics
#https://stackoverflow.com/questions/49032217/inner-joining-two-sf-objects-by-non-sf-column

jn <- env %>%  as.data.frame() %>%  select(GEOID20, mean_temp, mean_pm25) %>%  inner_join(as.data.frame(dem)) %>% st_sf(sf_column_name = 'geometry')

#compute smoothed pm2.5 and temperature
jn %<>% st_sf(sf_column_name = 'geometry')


```

```{r}

# Fuctions from Luis's
# Kriging

# Helper functions

spherical_variogram <- function (n, ps, r) function (h) {
  h <- h / r
  n + ps * ifelse(h < 1, 1.5 * h - .5 * h ^ 3, 1)
}

gaussian_variogram <- function (n, ps, r)
  function (h) n + ps * (1 - exp(-(h / r) ^ 2))


exponential_variogram <- function (n, ps, r)
  function (h) n + ps * (1 - exp(-(h / r)))




# solves `A * x = v` where `C = chol(A)` is the Cholesky factor:
chol_solve <- function (C, v) backsolve(C, backsolve(C, v, transpose = TRUE)) # the solution of triangular system.The result will be a vector if 'x' is a vector and a matrix if 'x' is a matrix.

kriging_smooth_spherical <- function (formula, data, ...) {
  # formula <- mean_pm25 ~ 1
  # data <- env
  v <- variogram(formula, data)
  v_fit <- fit.variogram(v, vgm("Sph"))
  v_f <- spherical_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
  #Sigma <- v_f(as.matrix(dist(coordinates(data)))) # previous code
  Sigma <- v_f(as.matrix(dist(matrix(unlist(data$geometry), ncol = 2, byrow = TRUE)))) # semivariogram
  Sigma <- sum(v_fit$psill) - Sigma # prior variance
  tau2 <- v_fit$psill[1] # residual variance
  C <- chol(tau2 * diag(nrow(data)) + Sigma)
  y <- model.frame(formula, data)[, 1] # response
  x <- model.matrix(formula, data)
  # generalized least squares:
  beta <- coef(lm.fit(backsolve(C, x, transpose = TRUE),
                      backsolve(C, y, transpose = TRUE))) # prior mean

  Sigma_inv <- chol2inv(chol(Sigma))
  C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
  # posterior mean (smoother):
  mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
  list(smooth = mu, prior_mean = beta)
}


kriging_smooth_gaussian <- function (formula, data, ...) {
  # formula <- mean_pm25 ~ 1
  # data <- env
  v <- variogram(formula, data)
  v_fit <- fit.variogram(v, vgm("Gau"))
  v_f <- gaussian_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
  Sigma <- v_f(as.matrix(dist(matrix(unlist(data$geometry), ncol = 2, byrow = TRUE)))) # semivariogram
  Sigma <- sum(v_fit$psill) - Sigma # prior variance
  tau2 <- v_fit$psill[1] # residual variance
  C <- chol(tau2 * diag(nrow(data)) + Sigma)
  y <- model.frame(formula, data)[, 1] # response
  x <- model.matrix(formula, data)
  # generalized least squares:
  beta <- coef(lm.fit(backsolve(C, x, transpose = TRUE),
                      backsolve(C, y, transpose = TRUE))) # prior mean

  Sigma_inv <- chol2inv(chol(Sigma))
  C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
  # posterior mean (smoother):
  mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
  list(smooth = mu, prior_mean = beta)}



kriging_smooth_exponential <- function (formula, data, ...) {
  formula <- mean_pm25 ~ 1
  data <- env
  v <- variogram(formula, data)
  v_fit <- fit.variogram(v, vgm("Exp"))

  v_f <- exponential_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])

  Sigma <- v_f(as.matrix(dist(matrix(unlist(data$geometry), ncol = 2, byrow = TRUE)))) # semivariogram
  Sigma <- sum(v_fit$psill) - Sigma # prior variance
  tau2 <- v_fit$psill[1] # residual variance
  C <- chol(tau2 * diag(nrow(data)) + Sigma)
  y <- model.frame(formula, data)[, 1] # response
  x <- model.matrix(formula, data)
  # generalized least squares:
  beta <- coef(lm.fit(backsolve(C, x, transpose = TRUE),
                      backsolve(C, y, transpose = TRUE))) # prior mean

  Sigma_inv <- chol2inv(chol(Sigma))
  C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
  # posterior mean (smoother):
  mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
  list(smooth = mu, prior_mean = beta)}

```

```{r}
env <- jn
env <- env[!is.na(env$mean_pm25),]

formula <- mean_pm25 ~ 1 + Mdn_Inc_s + Mdn_Inc_r + MnrPrc_s + MnrPrc_r

v <- variogram(formula, env)
v_fit <- fit.variogram(v, vgm("Exp")) #'vgm':generate a variogram model or add to an existing model.
v_f <- exponential_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])

# check variogram and covariance
op <- par(mfrow = c(1, 2))
h <- seq(0, 26000, length = 100)
plot(v$dist, v$gamma,  pch = 19, col = "gray",
     xlab = "distance", ylab = "semivariogram")
lines(h, v_f(h))
abline(v = v_fit$range[2], col = "gray")
plot(h, sum(v_fit$psill) - v_f(h), type = "l",
     xlab = "distance", ylab = "covariogram",
     ylim = c(0, sum(v_fit$psill)))
points(0, sum(v_fit$psill), pch = 19)
abline(v = v_fit$range[2], col = "gray")
par(op)


# check smoothing
ks <- kriging_smooth_exponential(formula, env)

y <- env$mean_pm25
op <- par(mfrow = c(1, 2))
plot(ks$smooth, y); abline(0, 1, col = "red")
plot(ks$smooth, type = "l", ylab = "y")
points(y, pch = 19, col = "gray")
abline(h = ks$prior_mean)
par(op)

# env$smooth <- ks$smooth
# breaks <- seq(4.5, 8, by = .5)
# tmap_mode("plot")
# tmap_arrange(
#   tm_shape(env) +
#     tm_bubbles(col = "response", palette = "-RdYlBu", size = .3, breaks = breaks),
#   tm_shape(env) +
#     tm_bubbles(col = "smooth", palette = "-RdYlBu", size = .3, breaks = breaks)
# )
```



#Kriging Smooth Gaussian (outside of function)
```{r}
formula <- mean_pm25 ~ 1
data <- env

v <- variogram(formula, data)
v_fit <- fit.variogram(v, vgm("Gau"))
v_f <- gaussian_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
Sigma <- v_f(matrix(unlist(data$geometry), ncol = 2, byrow = TRUE)) # semivariogram
Sigma <- sum(v_fit$psill) - Sigma # prior variance
tau2 <- v_fit$psill[1] # residual variance
C <- chol(tau2 * diag(nrow(data)) + Sigma)
y <- model.frame(formula, data)[, 1] # response
x <- model.matrix(formula, data)
# generalized least squares:
beta <- coef(lm.fit(backsolve(C, x, transpose = TRUE),
                    backsolve(C, y, transpose = TRUE))) # prior mean

Sigma_inv <- chol2inv(chol(Sigma))
C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
# posterior mean (smoother):
mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
list(smooth = mu, prior_mean = beta)}



#ks <- kriging_smooth_gaussian(mean_pm25~ 1, env)

```