---
title: "Processing"
author: "Rose Determan"
date: "11/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(sf, stars,raster,rgdal,tmap, magrittr, dplyr)

getwd()
```

# Import Census Tracts
```{r}
#https://data.boston.gov/dataset/7156ac97-670d-4b9f-8070-6a1264e5fb91/resource/1721fbb7-ee56-4a61-9e1b-2f2342d202d1/download/census2020_tracts.zip
tracts <- st_read("Census2020_Tracts/Census2020_tracts.shp")
```

# Import Landsat Temperature Raster
```{r}
#https://doi.org/10.5066/P960F8OC
#https://doi.org/10.5066/P960F8OC

fp1 <- "Surface_Temp/LC08_CU_030005_20210812_20210822_02_ST/LC08_CU_030005_20210812_20210822_02_ST_B10.TIF"
temp1=raster(fp1)

fp2 <- "Surface_Temp/LC08_CU_030006_20210812_20210822_02_ST/LC08_CU_030006_20210812_20210822_02_ST_B10.TIF"
temp2=raster(fp2)

#merge the two rasters 
x <- list(temp1, temp2)
names(x) <- c("x", "y")
x$filename <- 'test.tif'
x$overwrite <- TRUE
merge_temp <- do.call(merge, x)

#plot to double check the merge
#plot(m)
```


# Import PM 2.5 raster
```{r}
fp3 <- "PM25/V4NA03_PM25_NA_201801_201812-RH35-NoNegs/V4NA03_PM25_NA_201801_201812-RH35-NoNegs.asc"


pm2.5 <- raster(fp3)
```

# Use extract function 
Do the equivalent of QGIS's zonal stats. Calculate the mean of each census tract. Join the dataframe with mean temperatures to the census tracts shapefile. 
https://www.neonscience.org/resources/learning-hub/tutorials/dc-crop-extract-raster-data-r
```{r}
# Temperature
temp_ex <- raster::extract(x=merge_temp, y=tracts, fun=mean, df=TRUE)
temp_ex <- rename(temp_ex,OBJECTID = ID,  mean_temp =test)
tracts_jn <- left_join(tracts, temp_ex)


# PM 2.5
pm_ex <- raster::extract(x=pm2.5, y=tracts_jn, fun=mean, df=TRUE)
pm_ex <- rename(pm_ex,OBJECTID = ID,  mean_pm25 =V4NA03_PM25_NA_201801_201812.RH35.NoNegs)
tracts_jn <- left_join(tracts_jn, pm_ex)
```





# Plot the mean temp for each census tract
```{r}
tmap_mode("view")
 tm_shape(tracts_jn)+
    tm_polygons("mean_temp") + 
    tm_borders(col="#000000", lwd=0.2)
```

```{r}
tmap_mode("view")
 tm_shape(tracts_jn)+
    tm_polygons("mean_pm25") + 
    tm_borders(col="#000000", lwd=0.2)

```
