---
title: "kriging"
author: "environment"
date: "11/7/2021"
output: html_document
---
# Upload needed packages and source 'processing' file
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(sp) # spatial point data frames
library(gstat) # variogram estimation
library(tmap)
library(geosphere)
library(sf)
library(tidyverse)
library(magrittr)
library(arm)
```

# combine the data
```{r}
env <- st_read("env.shp")
env <- env[!is.na(env$mean_pm25),] #Remove rows with null columns
env <- st_centroid(env) # Calculate centroids
# epsg_wgs84 <- 4326
# env <- env %>% st_transform(epsg_wgs84)
# ggplot(env) + geom_sf()


dem <- st_read("Demographics_smoothed_addtre_cnp/DemographicsSmoothed_trecnp.shp")
dem <- st_centroid(dem)
#https://stackoverflow.com/questions/49032217/inner-joining-two-sf-objects-by-non-sf-column

#join selected environment columns to demographics
env_dub <- as.data.frame(env)
env_sub <- env_dub[,c('GEOID20','mean_temp','mean_pm25')]
jn <- env_sub  %>% inner_join(as.data.frame(dem)) %>% st_sf(sf_column_name = 'geometry') 
jn %<>% st_sf(sf_column_name = 'geometry')

#Standardize the coordinate system used
epsg_wgs84 <- 4326
jn <- jn %>% st_transform(epsg_wgs84)
```

```{r}
#Spherical and Gaussian Variogram functions

spherical_variogram <- function (n, ps, r) function (h) {
  h <- h / r
  n + ps * ifelse(h < 1, 1.5 * h - .5 * h ^ 3, 1)
}

gaussian_variogram <- function (n, ps, r)
  function (h) n + ps * (1 - exp(-(h / r) ^ 2))


exponential_variogram <- function (n, ps, r)
  function (h) n + ps * (1 - exp(-(h / r)))


# v <- variogram(qlogis(MinorPerc) ~ 1, centroids)

#Calculate variograms 
formula <- mean_pm25 ~ 1 # + Mdn_Inc_s + Mdn_Inc_r + MnrPrc_s + MnrPrc_r
dt <- env
v <- variogram(formula, env)
v_fit <- fit.variogram(v, vgm("Sph")) #'vgm':generate a variogram model or add to an existing model.
v_f <- spherical_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2]) #Create spherical variograms

#Plot the variograms
op <- par(mfrow = c(1, 2))
h <- seq(0, 26000, length = 1000)

plot(v$dist, v$gamma,  pch = 19, col = "gray",
     xlab = "distance", ylab = "semivariogram") # main = "Minority Percentage"
lines(h, v_f(h))
abline(v = v_fit$range[2], col = "gray")
plot(h, sum(v_fit$psill) - v_f(h), type = "l",
     xlab = "distance", ylab = "covariogram",
     ylim = c(0, sum(v_fit$psill)))
points(0, sum(v_fit$psill), pch = 19)
abline(v = v_fit$range[2], col = "gray")
par(op)


# solves `A * x = v` where `C = chol(A)` is the Cholesky factor:
chol_solve <- function (C, v) backsolve(C, backsolve(C, v, transpose = TRUE)) # the solution of triangular system.The result will be a vector if 'x' is a vector and a matrix if 'x' is a matrix.

# old kriging function
# kriging_smooth_spherical <- function (formula, data, ...) {
#   # formula <- mean_pm25 ~ 1
#   # data <- env
#   v <- variogram(formula, data)
#   v_fit <- fit.variogram(v, vgm("Sph"))
#   v_f <- spherical_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
#   #Sigma <- v_f(as.matrix(dist(coordinates(data)))) # previous code
#   Sigma <- v_f(as.matrix(dist(matrix(unlist(data$geometry), ncol = 2, byrow = TRUE)))) # semivariogram
#   Sigma <- sum(v_fit$psill) - Sigma # prior variance
#   tau2 <- v_fit$psill[1] # residual variance
#   C <- chol(tau2 * diag(nrow(data)) + Sigma)
#   y <- model.frame(formula, data)[, 1] # response
#   x <- model.matrix(formula, data)
#   # generalized least squares:
#   beta <- coef(lm.fit(backsolve(C, x, transpose = TRUE),
#                       backsolve(C, y, transpose = TRUE))) # prior mean
# 
#   Sigma_inv <- chol2inv(chol(Sigma))
#   C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
#   # posterior mean (smoother):
#   mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
#   list(smooth = mu, prior_mean = beta)
# }

#New Kriging Function
kriging_smooth_spherical <- function (formula, data, ...) {
  # formula <- mean_pm25 ~ 1
  # data <- env
  v <- variogram(formula, data)
  v_fit <- fit.variogram(v, vgm("Sph", ...))
  v_f <- spherical_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
  
  Sigma <- v_f(as.matrix(dist(st_coordinates(data)))) # semivariogram
  Sigma <- sum(v_fit$psill) - Sigma # prior variance
  tau2 <- v_fit$psill[1] # residual variance
  C <- chol(tau2 * diag(nrow(data)) + Sigma)
  y <- model.frame(formula, data)[, 1] # response
  x <- model.matrix(formula, data)
  # generalized least squares:
  xt <- backsolve(C, x, transpose = TRUE)
  beta <- coef(lm.fit(xt, backsolve(C, y, transpose = TRUE))) # prior mean
  names(beta) <- colnames(x)
  beta_se <- sqrt(diag(chol2inv(chol(crossprod(xt)))))
  
  chol_sigma <- chol(Sigma)
  Sigma_inv <- chol2inv(chol_sigma)
  C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
  # posterior mean (smoother):
  mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
  
  sinv_mu <- chol_solve(chol_sigma, mu - x %*% beta)
  krige <- function (new_data) { # prediction function
    D <- apply(coordinates(data), 1,
               function (coord) apply(st_coordinates(new_data), 1, dist2, coord))
    V <- sum(v_fit$psill) - v_f(D)
    
    t <- delete.response(terms(formula))
    xp <- model.matrix(t, model.frame(t, new_data))
    drop(xp %*% beta + V %*% sinv_mu)
  }
  
  list(smooth = mu, prior_coef = beta, prior_coef_se = beta_se,
       variogram = v_fit, krige = krige)
}

# 
# kriging_smooth_gaussian <- function (formula, data, ...) {
#   # formula <- mean_pm25 ~ 1
#   # data <- env
#   v <- variogram(formula, data)
#   v_fit <- fit.variogram(v, vgm("Gau"))
#   v_f <- gaussian_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
#   Sigma <- v_f(as.matrix(dist(matrix(unlist(data$geometry), ncol = 2, byrow = TRUE)))) # semivariogram
#   Sigma <- sum(v_fit$psill) - Sigma # prior variance
#   tau2 <- v_fit$psill[1] # residual variance
#   C <- chol(tau2 * diag(nrow(data)) + Sigma)
#   y <- model.frame(formula, data)[, 1] # response
#   x <- model.matrix(formula, data)
#   # generalized least squares:
#   beta <- coef(lm.fit(backsolve(C, x, transpose = TRUE),
#                       backsolve(C, y, transpose = TRUE))) # prior mean
# 
#   Sigma_inv <- chol2inv(chol(Sigma))
#   C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
#   # posterior mean (smoother):
#   mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
#   list(smooth = mu, prior_mean = beta)}
# 
# 
# 
# kriging_smooth_exponential <- function (formula, data, ...) {
#   formula <- mean_pm25 ~ 1 + Mdn_Inc_s + Mdn_Inc_r + MnrPrc_s + MnrPrc_r
#   data <- env
#   v <- variogram(formula, data)
#   v_fit <- fit.variogram(v, vgm("Exp"))
# 
#   v_f <- exponential_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])
# 
#   Sigma <- v_f(as.matrix(dist(matrix(unlist(data$geometry), ncol = 2, byrow = TRUE)))) # semivariogram
#   Sigma <- sum(v_fit$psill) - Sigma # prior variance
#   tau2 <- v_fit$psill[1] # residual variance
#   C <- chol(tau2 * diag(nrow(data)) + Sigma)
#   y <- model.frame(formula, data)[, 1] # response
#   x <- model.matrix(formula, data)
#   # generalized least squares:
#   beta <- coef(lm.fit(backsolve(C, x, transpose = TRUE),
#                       backsolve(C, y, transpose = TRUE))) # prior mean
# 
#   Sigma_inv <- chol2inv(chol(Sigma))
#   C <- chol(Sigma_inv + diag(nrow(data)) / tau2)
#   # posterior mean (smoother):
#   mu <- drop(chol_solve(C, y / tau2 + Sigma_inv %*% x %*% beta))
#   list(smooth = mu, prior_mean = beta)}

```

```{r}
# check smoothing: still not work
ks <- kriging_smooth_spherical(formula, dt)

y <- env$mean_pm25
op <- par(mfrow = c(1, 2))
plot(ks$smooth, y); abline(0, 1, col = "red")
plot(ks$smooth, type = "l", ylab = "y")
points(y, pch = 19, col = "gray")
abline(h = ks$prior_mean)
par(op)

#Add smoothing and residuals to datasets
jn$mean_pm25_smooth <- ks$smooth
jn$mean_pm25_resid <- jn$mean_pm25 - jn$mean_pm25_smooth 

#Plots that show smoothing
ggplot(jn) + geom_sf(aes(fill = mean_pm25)) + 
  scale_fill_distiller(palette="Reds", trans = "reverse")

ggplot(jn) + geom_sf(aes(fill = mean_pm25_smooth)) + 
  scale_fill_distiller(palette="Reds", trans = "reverse")
```

```{r}
#Check if Tree Canopy can be predicted from ...
v <- variogram(qlogis(Tre_Cnp) ~  Mdn_Inc_s  + Mdn_Inc_r + MnrPrc_s + MnrPrc_r + mean_pm25, jn) # do we need add residual? do we need add "1+", and what I heard is log(TotalPp) or log(PpDnsty)? 

v_fit <- fit.variogram(v, vgm("Sph"))
v_f <- spherical_variogram(v_fit$psill[1], v_fit$psill[2], v_fit$range[2])

op <- par(mfrow = c(1, 2))
h <- seq(0, 200, length = 1000) 

plot(v$dist, v$gamma,  pch = 19, col = "gray",
     xlab = "distance", ylab = "semivariogram", main = "Tree Canopy")
lines(h, v_f(h))
abline(v = v_fit$range[2], col = "gray")

# check smoothing: still not work
formula <- qlogis(Tre_Cnp) ~  Mdn_Inc_s  + Mdn_Inc_r + MnrPrc_s + MnrPrc_r + mean_pm25
dt <- jn
ks <- kriging_smooth_spherical(formula, dt)

y <- jn$mean_pm25
op <- par(mfrow = c(1, 2))
plot(ks$smooth, y); abline(0, 1, col = "red") # this smooth is about the combination of predictors above? 
plot(ks$smooth, type = "l", ylab = "y")
points(y, pch = 19, col = "gray") # what's wrong
abline(h = ks$prior_coef) # ks's prior_coef's mean_pm25
par(op)

# #Add smoothing and residuals to datasets
# jn$mean_pm25_smooth <- ks$smooth
# jn$mean_pm25_resid <- jn$mean_pm25 - jn$mean_pm25_smooth 
# 
# 
# #Plots that show smoothing
# ggplot(jn) + geom_sf(aes(fill = mean_pm25)) + 
#   scale_fill_distiller(palette="Reds", trans = "reverse")
# 
# ggplot(jn) + geom_sf(aes(fill = mean_pm25_smooth)) + 
#   scale_fill_distiller(palette="Reds", trans = "reverse")

```


